version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run: &yarn_install
          name: Install dependencies
          command: yarn
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: yarn test
  node-12:
    <<: *test
    docker:
      - image: node:12
  node-10:
    <<: *test
    docker:
      - image: node:10
  prettier:
    <<: *test
    steps:
      - checkout
      - *yarn_install
      - run:
          name: Check prettier
          command: yarn format:check
  cache:
    <<: *test
    steps:
      - checkout
      - *yarn_install
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
  release:
    <<: *test
    steps:
      - checkout
      - *restore_cache
      - *yarn_install
      - run:
          name: release
          command: yarn release || true

workflows:
  version: 2
  nbx:
    jobs:
      - node-latest
      - node-12
      - node-10
      - prettier
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - release:
          requires:
            - node-latest
            - node-12
            - node-10
            - prettier
          filters:
            branches:
              only: master
